### ISSUE TITLE
流式推理

### ISSUE THREAD

**Issue by kaidachen** [wangtianrui/HGCN#1]
请问有验证HGCN流式推理的效果嘛？

**Comment by wangtianrui** [comment]
我文章里的结果都是测的流式的

**Comment by kaidachen** [comment]
流式推理的脚本有开源嘛？

**Comment by wangtianrui** [comment]
抱歉，流式推理相关的代码，在公司一个项目中有使用到，并且整个项目正在申请专利（我们最终是用tflite做的工程部署），这个仓库的目的是辅助阅读文章的，所以流式处理不方便开源，但是整体需要改的东西不多，我可以告诉你。

开源模型代码如果需要改为流式处理主要有如下两个方面需要改一下：
1、把前一帧的每层卷积（正反卷积都需要）的最后一帧保存下来作为参数传给下一次的调用，并补到下一次的因果卷积前面；
2、LSTM和GRU的h也需要作为参数传给下一次调用（和1一样临时保存起来就行）

整体工程量不大，祝你成功

**Comment by kaidachen** [comment]
十分感谢！
